# clear && docker kill rabbitmq && docker rm rabbitmq && docker compose up -d
networks:
    default:
        name: app
        driver: bridge

services:
    rabbitmq:
        image: 'rabbitmq:3-management'
        container_name: 'rabbitmq'
        restart: 'unless-stopped'
        environment:
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: root
        ports:
        - '5672:5672'
        - '15672:15672'