networks:
    default:
        name: 'app'
        driver: 'bridge'

services:
    mysql80:
        image: 'mysql:8.0-debian'
        ports:
        - '3306:3306'
        restart: 'always'
        container_name: 'mysql80'
        volumes:
        - 'mysql80:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'

volumes:
    mysql80:
